### PR TITLE
change ALGORITHM tag into comment

### PR DESCRIPTION
**Pull request by ly015**

### CODE REVIEW

**Comment by innerlee** [comment]
Have you tested locally?

**Comment by ly015** [comment]
The docs have been autoformatted accidentally. I will push a commit to fix it.

**Comment by innerlee** [comment]
The formatting is okay to me. Pls run 

```bash
cd docs
make html
```

and check the generated htmls are good.

**Comment by ly015** [comment]
> The formatting is okay to me. Pls run
> 
> ```shell
> cd docs
> make html
> ```
> 
> and check the generated htmls are good.

The locally built htmls look good to me, except that the model-zoo overview page is not generated so we don't known if the algorithm counts are correct.

**Comment by innerlee** [comment]
The important thing is the modelzoo

**Comment by innerlee** [comment]
The important thing is the modelzoo, which is the sole purpose of the tag

**Comment by innerlee** [comment]
Please also change the [backbone], [dataset], etc.

**Review by innerlee — APPROVED** [review]

**Comment by innerlee** [comment]
The linting failed btw

**Pull request merged**
