### PR TITLE
udpate reqs with missing deps

### PR DESCRIPTION
**Pull request by SMHendryx**
had to add some deps to the requirements to get a working installation. See https://github.com/open-mmlab/mmpose/issues/282

### CODE REVIEW

**Comment by innerlee** [comment]
* cython is used by dependencies, and it is not a runtime requirement
* technically speaking, mmcv-full is an dependency of mmdet, not mmpose. It is needed only for this demo, where mmdet is used to provide bboxes.
* torch is needed also, i guess.

Solution:
* ~~Cython~~
* ~~mmcv>=1.1.1~~, ~~mmcv-full~~
* add torch alongside torchvision

**Comment by SMHendryx** [comment]
ok, updated following your suggestion @innerlee

**Comment by innerlee** [comment]
image

**Comment by innerlee** [comment]
According to the error message, `torch` has to be removed here :/

**Review by innerlee — APPROVED** [review]

**Comment by OpenMMLab-Assistant-007** [comment]
Hi!
@SMHendryx 
First of all, we want to express our gratitude for your significant PR in the OpenMMLab project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA

If you have WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤

**Pull request merged**
