### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by dmitrysarov**

### CODE REVIEW

**Comment by innerlee** [comment]
Thanks!

**Comment by innerlee** [comment]
Could sign the cla so that we can merge it?

**Comment by dmitrysarov** [comment]
✅

**Comment by innerlee** [comment]
kindly ping, this now conflicts with master.

have you encounter problems signing the cla? if so, need any help?

**Comment by dmitrysarov** [comment]
Sorry, I was sure that I did! 
Looks like a bug in the assignment process.

**Comment by innerlee** [comment]
okay, let proceed and regard the checkbox in https://github.com/open-mmlab/mmpose/pull/28#issuecomment-663019205 as an agreement :)

**Comment by openmmlab-v** [comment]
Hi @dmitrysarov ！First of all, we want to express our gratitude for your significant PR in the mmpose project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/raweFPmdzG

If you are Chinese or have WeChat，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤

**Pull request merged**
