### PR TITLE
Add back resnet_coco metafile

### PR DESCRIPTION
**Pull request by cherryjm**

### CODE REVIEW

**Comment by innerlee** [comment]
What's the meaning of revert?

**Comment by cherryjm** [comment]
The metafile is deleted after reorganizing configs.

**Comment by innerlee** [comment]
Is this done by `git revert`?

**Comment by jin-s13** [comment]
The metafiles should be automatically generated (by codes).

**Comment by cherryjm** [comment]
This is not done by git revert, since the path to configs has changed.
Will add a script later. This PR is just to revert the metafile that has been added before.

**Comment by ly015** [comment]
@cherryjm Could you please also test that mim can access and parse the metafiles properly?

**Comment by cherryjm** [comment]
@ly015 Now the metafiles can be parsed successfully.

**Review by ly015 — APPROVED** [review]

**Pull request merged**
