### PR TITLE
Lz/skps/  new model

### PR DESCRIPTION
**Pull request by 610265158**
## Motivation

A new kps model that achieves 0.394 within WLFW, and it predict a heatmap and a offsidemap. And i name it as simple keypoints(skps)

## Modification

codes placed in project/skps

## Checklist

**Before PR**:

- [x] I have read and followed the workflow indicated in the [CONTRIBUTING.md](https://github.com/open-mmlab/mmpose/blob/master/.github/CONTRIBUTING.md) to create this PR.
- [x] Pre-commit or linting tools indicated in [CONTRIBUTING.md](https://github.com/open-mmlab/mmpose/blob/master/.github/CONTRIBUTING.md) are used to fix the potential lint issues.
- [ ] Bug fixes are covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] New functionalities are covered by complete unit tests. If not, please add more unit tests to ensure correctness.
- [x] The documentation has been modified accordingly, including docstring or example tutorials.

**After PR**:

- [ ] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Comment by Tau-J** [comment]
Thanks for your contribution. Your PR branch is based on main, which lags behind our dev-1.x. Would you mind rebasing your PR branch following our [guide](https://mmpose.readthedocs.io/en/1.x/contribution_guide.html#create-a-development-branch)?

**Comment by 610265158** [comment]
Is it ok now? The code is based from dev-1.x, when i start .

**Comment by 610265158** [comment]
i will reopen a new pr

**Comment by 610265158** [comment]
i will reopen a new pr

**Pull request closed without merging**
