### PR TITLE
[Fix] fix data transform

### PR DESCRIPTION
**Pull request by hebin110400**
## Checklist

**Before PR**:

- [ ] I have read and followed the workflow indicated in the [CONTRIBUTING.md](https://github.com/open-mmlab/mmpose/blob/master/.github/CONTRIBUTING.md) to create this PR.
- [ ] Pre-commit or linting tools indicated in [CONTRIBUTING.md](https://github.com/open-mmlab/mmpose/blob/master/.github/CONTRIBUTING.md) are used to fix the potential lint issues.
- [ ] Bug fixes are covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] New functionalities are covered by complete unit tests. If not, please add more unit tests to ensure correctness.
- [ ] The documentation has been modified accordingly, including docstring or example tutorials.

**After PR**:

- [ ] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Comment by ly015** [comment]
Thank you very much for your contribution! Could you please show an example case where it's necessary to explicitly convert the image to contiguous before channel permuting?

**Comment by Ben-Louis** [comment]
> Thank you very much for your contribution! Could you please show an example case where it's necessary to explicitly convert the image to contiguous before channel permuting?

If the image is flipped, the image array will become non-contiguous, which cannot be converted into a pytorch tensor using `torch.from_numpy`
微信图片_20230404160315

**Comment by Ben-Louis** [comment]
BTW, I've tested this implementation and found that it is still faster than the original one that uses `np.transpose`.

**Review by Tau-J — APPROVED** [review]

**Comment by OpenMMLab-Assistant-004** [comment]
Hi @hebin110400 ！First of all, we want to express our gratitude for your significant PR in the mmpose project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/raweFPmdzG

If you have WeChat，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤

**Pull request merged**
