### PR TITLE
[Feature] Add tool for converting labelme data to coco format

### PR DESCRIPTION
**Pull request by lllrj**
## Motivation
Provides a tool for labelme2coco that does not include the ability to assemble initially scattered labelme files into a single file.

## Checklist

**Before PR**:

- [x] I have read and followed the workflow indicated in the [CONTRIBUTING.md](https://github.com/open-mmlab/mmpose/blob/master/.github/CONTRIBUTING.md) to create this PR.
- [x] Pre-commit or linting tools indicated in [CONTRIBUTING.md](https://github.com/open-mmlab/mmpose/blob/master/.github/CONTRIBUTING.md) are used to fix the potential lint issues.
- [ ] Bug fixes are covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] New functionalities are covered by complete unit tests. If not, please add more unit tests to ensure correctness.
- [ ] The documentation has been modified accordingly, including docstring or example tutorials.

**After PR**:

- [ ] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Comment by Ben-Louis** [comment]
Thank you so much for your valuable contribution. Could you please sign the CLA mentioned above, so that we can accept your contribution?

**Comment by lllrj** [comment]
> Thank you so much for your valuable contribution. Could you please sign the CLA mentioned above, so that we can accept your contribution?

I have signed the CLA, and the page told me that I have.But I don't know why it update yet.

**Comment by Ben-Louis** [comment]
> I have signed the CLA, and the page told me that I have.But I don't know why it update yet.

Have you linked your Git email with your GitHub account? 
If not, you can view your Git email by using the command `git config user.email`. Once you have your Git email, you can add it to your GitHub account by visiting the URL https://github.com/settings/emails. 

After the above steps, the CLA status may be updated

**Comment by lllrj** [comment]
> > I have signed the CLA, and the page told me that I have.But I don't know why it update yet.
> 
> Have you linked your Git email with your GitHub account? If not, you can view your Git email by using the command `git config user.email`. Once you have your Git email, you can add it to your GitHub account by visiting the URL https://github.com/settings/emails.
> 
> After the above steps, the CLA status may be updated

In fact,I have done what you suggest two hours ago,but CLA has not passed.
When I inputted `git config --list`, I got:
`user.name=“lllrj”`
`user.email=“1018652162@qq.com”` and else
it matches my github acount but it didn't work

**Comment by Ben-Louis** [comment]
I think the issue could be the usage of full-width quotation marks in your email as in https://github.com/open-mmlab/mmpose/pull/1800. To resolve this, you may have to modify your email address and re-commit your changes by following the steps below:
1. Change your email in the terminal: `git config --global user.email 1018652162@qq.com`
2. Withdraw the latest commit: `git reset --soft HEAD^`
3. Re-commit: `git commit -m labelme2coco`
4. Forcely push the new commit

**Comment by lllrj** [comment]
> I think the issue could be the usage of full-width quotation marks in your email as in #1800. To resolve this, you may have to modify your email address and re-commit your changes by following the steps below:
> 
> 1. Change your email in the terminal: `git config --global user.email 1018652162@qq.com`
> 2. Withdraw the latest commit: `git reset --soft HEAD^`
> 3. Re-commit: `git commit -m labelme2coco`
> 4. Forcely push the new commit

I think you are right and I will pr it again

**Pull request closed without merging**
