### PR TITLE
[Feature] add Swin backbone and FPN neck

### PR DESCRIPTION
**Pull request by yumendecc**
## Motivation

- Add Swin Transformer backbone [ICCV 2021](https://iccv2021.thecvf.com/) into the repository
- Support FPN neck

Codes derived from MMDetection.

## Modification

- `mmpose/models/backbones/swin.py`
- `mmpose/models/necks/fpn.py`
- `mmpose/models/utils/ckpt_converter.py`
- `mmpose/models/utils/transformer.py`

## Checklist

**Before PR**:

- [ ] I have read and followed the workflow indicated in the [CONTRIBUTING.md](https://github.com/open-mmlab/mmpose/blob/master/.github/CONTRIBUTING.md) to create this PR.
- [ ] Pre-commit or linting tools indicated in [CONTRIBUTING.md](https://github.com/open-mmlab/mmpose/blob/master/.github/CONTRIBUTING.md) are used to fix the potential lint issues.
- [ ] Bug fixes are covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] New functionalities are covered by complete unit tests. If not, please add more unit tests to ensure correctness.
- [ ] The documentation has been modified accordingly, including docstring or example tutorials.

**After PR**:

- [ ] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Comment by ly015** [comment]
Hi @yumendecc , we are working on the code review, and will try training swin-pose models based on this PR as a verification. You needn't worry about the branch conflicts, which we will fix later.

**Comment by ly015** [comment]
@yumendecc It seems that the Feature Fusion Module in the paper has not been included in this PR. We would like to add it and update the config according to the settings in the paper. Then we will start verifying the model accuracy. Thanks again for your contribution and you are most welcome to review and leave comments on our modifications.

**Comment by yumendecc** [comment]
这个PR当时想是基于Swin Transformer和SimpleBaseline修改的，当时并没有留意到SWIN-POSE这个工作。。。。后面我会继续跟进这个pr



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yining ***@***.***&gt;; 
发送时间: 2022年4月27日(星期三) 凌晨0:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [open-mmlab/mmpose] [Feature] Add Swin-Pose backbone (PR #1300)





 
@yumendecc It seems that the Feature Fusion Module in the paper has not been included in this PR. We would like to add it and update the config according to the settings in the paper. Then we will start verifying the model accuracy. Thanks again for your contribution and you are most welcome to review and leave comments on our modifications.

**Comment by jin-s13** [comment]
> 这个PR当时想是基于Swin Transformer和SimpleBaseline修改的，当时并没有留意到SWIN-POSE这个工作。。。。后面我会继续跟进这个pr

I think that's fine. In this PR, we just focus on adding a Swin-Transformer backbone, instead of supporting SWIN-POSE. What do you think?

**Comment by ly015** [comment]
> > 这个PR当时想是基于Swin Transformer和SimpleBaseline修改的，当时并没有留意到SWIN-POSE这个工作。。。。后面我会继续跟进这个pr
> 
> I think that's fine. In this PR, we just focus on adding a Swin-Transformer backbone, instead of supporting SWIN-POSE. What do you think? @ly015

Actually, I am working on completing the Feature Fusion Module part. It should be no trouble since we can borrow the FPN code from mmdet too.

**Comment by ly015** [comment]
@yumendecc The git history of the branch seems incomplete. It seems that it's developed based on a shallow clone of mmpose. This may cause trouble when we try to merge this PR into master.

**Comment by ly015** [comment]
> @yumendecc The git history of the branch seems incomplete. It seems that it's developed based on a shallow clone of mmpose. This may cause trouble when we try to merge this PR into master.

We will rebase the PR onto dev-0.26 branch to solve the problem.

**Review by ly015 — APPROVED** [review]

**Comment by ly015** [comment]
@yumendecc @jin-s13 I have updated the experiment results and the documentation.

**Review by jin-s13 — APPROVED** [review]

**Comment by jin-s13** [comment]
This PR looks good to me in general, except that some minor modifications are required before merging.

**Comment by OpenMMLab-gd** [comment]
Dear yumendecc,
First of all, we want to express our gratitude for your significant PR in the MMPose project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.
If you are Chinese or have WeChat，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. We look forward to seeing you there! Join us ：https://discord.gg/raweFPmdzG
Thank you again for your contribution❤
Best regards！ @yumendecc

**Pull request merged**
