### PR TITLE
Dev 1.x

### PR DESCRIPTION
**Pull request by SicongLiu998**
## Motivation

When I trained a model based on AP-10K dataset, in testing part, I found the value of AP is abnormal. There is a bug in 474 line of mmpose/mmpose/evaluation/metrics/coco_metric.py

## Modification

Before:
for _, pred in zip(data_batch, predictions):

After:
for pred in predictions:

## Checklist

**Before PR**:

- [ ] I have read and followed the workflow indicated in the [CONTRIBUTING.md](https://github.com/open-mmlab/mmpose/blob/master/.github/CONTRIBUTING.md) to create this PR.
- [ ] Pre-commit or linting tools indicated in [CONTRIBUTING.md](https://github.com/open-mmlab/mmpose/blob/master/.github/CONTRIBUTING.md) are used to fix the potential lint issues.
- [ ] Bug fixes are covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] New functionalities are covered by complete unit tests. If not, please add more unit tests to ensure correctness.
- [ ] The documentation has been modified accordingly, including docstring or example tutorials.

**After PR**:

- [ ] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Comment by liqikai9** [comment]
@SicongLiu998 Hi, thanks for your contribution! 

However, the `dev-1.x` and `master` branchs are two very different versions and have many differences. Thus, this PR seems have lots of changed files.

Please follow this [guide](https://mmpose.readthedocs.io/en/1.x/notes/contribution_guide.html) to raise a PR to the **1.x** version. 

If you have any question during this process,  feel free to reach us~

**Comment by Ben-Louis** [comment]
Hi, thank you for your contribution :D

Could you please follow this [step-by-step guideline](https://sideways-swift-764.notion.site/MMPose-PR-92fb48d09bf94725a37a31ac22a7219d) to modify this PR or open a new PR? (we recommend the later since it is easier)

**Comment by ly015** [comment]
@SicongLiu998 Thank you very much for helping us improve mmpose 1.0. For now, this PR needs some slight modifications before we can review and merge it. Basically, to contribute codes to mmpose 1.0, please checkout a new branch from branch 1.x.. And the merge target of the PR should also be branch 1.x. Please refer to the documents shared by Ben-Louis and feel free to contact us if there are any other questions :)

**Comment by SicongLiu998** [comment]
> @SicongLiu998 Thank you very much for helping us improve mmpose 1.0. For now, this PR needs some slight modifications before we can review and merge it. Basically, to contribute codes to mmpose 1.0, please checkout a new branch from branch 1.x.. And the merge target of the PR should also be branch 1.x. Please refer to the documents shared by Ben-Louis and feel free to contact us if there are any other questions :)

I'm very sorry for the improper operation that brings inconvenience to your work. Recently, I am busy for an opening report. Please allow me to fix the problem in a few days. :D

**Comment by ly015** [comment]
@SicongLiu998 Hi, just a friendly check on the status. Is this PR still in your plan? Please let us know if there is anything we can help.

**Comment by Ben-Louis** [comment]
Hi @SicongLiu998, since the problem of `Ap10kCocoMetric` has been fixed in https://github.com/open-mmlab/mmpose/pull/1850, we are going to close this PR. Thank you again for your support to MMPose! Please feel free to contact us if you have any further advice or question about MMPose.

**Pull request closed without merging**
