### PR TITLE
[Feature] Add algebraic triangulation (multi-view 3D pose)

### PR DESCRIPTION
**Pull request by kristijanbartol**
## Motivation

Based on a current roadmap (#9), we want to add "Learnable Triangulation of Human Pose" ([link to paper](https://arxiv.org/abs/1905.05754)).

## Modification

For now, I created a new class in `models->detectors->multiview_pose.py`.

## Use cases (Optional)

The _algebraic triangulation_ is one of the two proposed models (the other is volumetric triangulation). The volumetric triangulation was the state-of-the-art of 3D human pose estimation task for a relatively long time. The algebraic triangulation is simpler, but still powerful model. Moreover, the volumetric triangulation depends on the algebraic triangulation (needs algebraic model to locate the root joint). Therefore, it is reasonable to first add the algebraic triangulation.

## Checklist

**Before PR**:

- [X] I have read and followed the workflow indicated in the [CONTRIBUTING.md](https://github.com/open-mmlab/mmpose/blob/master/.github/CONTRIBUTING.md) to create this PR.
- [X] Pre-commit or linting tools indicated in [CONTRIBUTING.md](https://github.com/open-mmlab/mmpose/blob/master/.github/CONTRIBUTING.md) are used to fix the potential lint issues.
- [ ] Bug fixes are covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] New functionalities are covered by complete unit tests. If not, please add more unit tests to ensure correctness.
- [ ] The documentation has been modified accordingly, including docstring or example tutorials.

**After PR**:

- [x] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Comment by jin-s13** [comment]
@kristijanbartol  
How is the project going? Is there anything we can help you with?

**Comment by kristijanbartol** [comment]
Hi @jin-s13 , thank you for your assistance and I apologize for inactivity. I planned to have time for this, but got burried under other obligations. I postponed it for the end of August. Is that acceptable? For now, it is seems clear how to implement the algebraic model.

**Comment by jin-s13** [comment]
Thank you! That's ok. We look forward to your contributions! Please don't hesitate to contact us if you have any questions.

**Comment by ly015** [comment]
Hi there, I hope everything is going well. Please let us know if there are any updates or if there is anything we can help with. Thank you very much!

**Comment by kristijanbartol** [comment]
I'm sorry, guys. I have to postpone this for later. It is still on my roadmap, but I have some higher priority tasks in the next few months.

**Comment by ly015** [comment]
There is no hurry :) BTW, we have pre-released [MMPose v1.0](https://github.com/open-mmlab/mmpose/tree/1.x) which involves a major refactoring and is in open beta now. Feel free to have a try if you still work on pose-related projects and any feedback will be appreciated! Thank you

**Pull request closed without merging**
