### PR TITLE
[Fix] fix the bug of 'sigma' and 'output file name' in bottom_up_img_demo.py

### PR DESCRIPTION
**Pull request by chenxinfeng4**
## Motivation

Fix the bugs while using the `bottom_up_img_demo.py`

## Modification

+ Use the custom `sigma` if user have defined it in config file.  It's vital especially when the keypoint number in custom dataset is the same as the default human pose.
+ fix the bug of `output file name`

### CODE REVIEW

**Review by jin-s13 — APPROVED** [review]

**Comment by jin-s13** [comment]
Thanks for your contribution! @chenxinfeng4 
Please sign CLA so that we can merge this change.

**Comment by ly015** [comment]
Thank you very much for your contribution. This PR is possibly partially duplicated with #1101 . Could you please rebase your branch onto master and solve the conflict?

**Comment by liqikai9** [comment]
Thanks for your contribution! @chenxinfeng4 
Your code is clearer than PR #1001. Could you please rebase your branch onto the **latest** master branch and solve the conflict?

**Review by liqikai9 — APPROVED** [review]

**Comment by chenxinfeng4** [comment]
I've solve the conflict in last MERGE (commit = a5d5eca). Please check it.

**Review by jin-s13 — APPROVED** [review]

**Comment by liqikai9** [comment]
> I've solve the conflict in last MERGE (commit = [a5d5eca](https://github.com/open-mmlab/mmpose/commit/a5d5eca032ade07dd9f2684bf1f3319c48c79722)). Please check it.

There seems to have some lint problem. You can follow this [guide](https://github.com/open-mmlab/mmpose/blob/master/.github/CONTRIBUTING.md#code-style)  to install `pre-commit hook `, which can check and format the code automatically on every commit.

**Pull request merged**
