### PR TITLE
[Feature] Add support for deepfashion2 dataset 

### PR DESCRIPTION
**Pull request by ATang0729**
## Motivation

Recently, I'm using `mmyolo v0.5.0` and `mmpose v0.x`, based on dataset `DeepFashion2`. It's known that the corresponding version of `MMCV` of these two are incompatible. So I changed my version of `mmpose` to 1.x. However, I found that the new version doesn't support dataset `DeeapFashion2` yet, which has already been supported by the old one ([see here](https://github.com/open-mmlab/mmpose/tree/master/configs/fashion/2d_kpt_sview_rgb_img/topdown_heatmap/deepfashion2)).

So I added several configs to enable this new version to train the deepfashion2 dataset. And hope it can help when somebody need to do more complicated fashion landmark tasks.

## Modification

The modifications are mainly in the folder `configs`
- a new dataset config `deepfashion2.py` in `configs/_base_/datasets`
- several config files in `configs/fashion_2d_keypoint/topdown_heatmap/deepfashion2` folder for different tasks and are namely based on the [rule](https://mmpose.readthedocs.io/zh_CN/latest/user_guides/configs.html#id9).

Others are as below:

- translate ["Inference.md"](docs/zh_cn/user_guides/inference.md) in "user guides" into Chinese
- create a new dataset class in `mmpose/datasets/datasets/fashion/__init__.py` and `mmpose/datasets/datasets/fashion/deepfashion2_dataset.py`
- few line wrappings are made in `projects/yolox-pose` automatically during the commitment

The description of usage is written in `docs/en/dataset_zoo/2d_fashion_landmark.md` and a copy is made in `docs/zh_cn/dataset_zoo/2d_fashion_landmark.md`

Due to limited time, I would share pre-trained models and the corresponding training logs later.

## BC-breaking (Optional)

No

## Checklist

**Before PR**:

- [x] I have read and followed the workflow indicated in the [CONTRIBUTING.md](https://github.com/open-mmlab/mmpose/blob/master/.github/CONTRIBUTING.md) to create this PR.
- [x] Pre-commit or linting tools indicated in [CONTRIBUTING.md](https://github.com/open-mmlab/mmpose/blob/master/.github/CONTRIBUTING.md) are used to fix the potential lint issues.
- [x] Bug fixes are covered by unit tests, the case that causes the bug should be added in the unit tests.
- [x] New functionalities are covered by complete unit tests. If not, please add more unit tests to ensure correctness.
- [x] The documentation has been modified accordingly, including docstring or example tutorials.

**After PR**:

- [x] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Comment by Tau-J** [comment]
Thanks a lot for your contribution. Could you remove the Chinese comments in config files? We will review this PR asap.

**Comment by ATang0729** [comment]
how can I share pre-trained models and the corresponding training logs

**Comment by Ben-Louis** [comment]
> how can I share pre-trained models and the corresponding training logs

Hi @ATang0729, to share your pre-trained models and associated training logs, you can upload the checkpoint files and log data to a cloud storage service such as Google Drive, OneDrive, or BaiduYun. Once uploaded, simply generate a shareable link and provide it to us. Thank you very much!

**Comment by Tau-J** [comment]
BTW, please provide the `.json` in terms of training logs, instead of the `.log`

**Comment by ATang0729** [comment]
> BTW, please provide the `.json` in terms of training logs, instead of the `.log`

copy that. I will update ASAP

**Comment by ATang0729** [comment]
I found that the inference result may be wrong and even lead to a disaster when using MMPoseInferencer in the way as below because of the disability of specifying of `bbox`.
```python
inferencer = MMPoseInferencer(
    pose2d=${pose_config},
    pose2d_weights=${pose_checkpoint},
    det_model=${dect_config},
    det_weights=${dect_checkpoint}
)
```
I thought that the func `vis_pose_result` in file [inference.py](https://github.com/open-mmlab/mmpose/blob/21aeeb455fe198083cd3a16de9c9fc00bade8706/mmpose/apis/inference.py), which has been removed in version 1.x, may solve this problem.
So I wrote an extension called `vis_pred_save.py`. I'm wondering if I should commit to this while worrying the extension may probably not fit your rules. 
f977668930d1f3bcdbe17424e1047bd

**Comment by OpenMMLab-Assistant-004** [comment]
Hi @ATang0729 ！We are grateful for your efforts in helping improve mmpose open-source project during your personal time. 

Welcome to join OpenMMLab Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA
If you have a WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）

Thank you again for your contribution❤

**Comment by Ben-Louis** [comment]
Hi @ATang0729, top-down pose estimation models are typically used together with object detectors. We will improve Inferencer by incorporating support for specified bounding boxes. On the other hand, utilizing bottom-up or one-stage pose estimation approaches can avoid this issue.

**Comment by Tau-J** [comment]
BTW, @ATang0729 Could you pull the latest `dev-1.x` branch to enable CI test?

**Comment by ATang0729** [comment]
> BTW, @ATang0729 Could you pull the latest `dev-1.x` branch to enable CI test?

I’ll do it later

**Review by Tau-J — APPROVED** [review]

**Pull request merged**
