### PR TITLE
Fix broken links

### PR DESCRIPTION
**Pull request by doufengqi**
## Checklist

**Before PR**:

- [ ] I have read and followed the workflow indicated in the [CONTRIBUTING.md](https://github.com/open-mmlab/mmpose/blob/master/.github/CONTRIBUTING.md) to create this PR.
- [ ] Pre-commit or linting tools indicated in [CONTRIBUTING.md](https://github.com/open-mmlab/mmpose/blob/master/.github/CONTRIBUTING.md) are used to fix the potential lint issues.
- [ ] Bug fixes are covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] New functionalities are covered by complete unit tests. If not, please add more unit tests to ensure correctness.
- [ ] The documentation has been modified accordingly, including docstring or example tutorials.

**After PR**:

- [ ] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Comment by doufengqi** [comment]
The previous link cannot be opened (not an isolated case), here is the repair link

**Comment by jin-s13** [comment]
I tried the previous link in the (md file)[https://github.com/open-mmlab/mmpose/blob/master/docs/en/tasks/2d_animal_keypoint.md] just now, but it worked fine...

**Comment by ly015** [comment]
@doufengqi Thank you very much for your help. I think the original link is not broken. It links to a section of the official site, instead of the download URL. I think using the download URL here could be more clear and more convenient for users.

**Comment by doufengqi** [comment]
> @doufengqi Thank you very much for your help. I think the original link is not broken. It links to a section of the official site, instead of the download URL. I think using the download URL here could be more clear and more convenient for users.

We tried many times to visit yesterday and failed, but today it suddenly became better. However, my new link can directly download the target file, and people don't need to click in to find the download link.

**Comment by doufengqi** [comment]
> I tried the previous link in the [md file](https://github.com/open-mmlab/mmpose/blob/master/docs/en/tasks/2d_animal_keypoint.md) just now, but it worked fine...

We tried many times to visit yesterday and failed, but today it suddenly became better. However, my new link can directly download the target file, and people don't need to click in to find the download link.

**Pull request closed without merging**
