### PR TITLE
add rhd hand dataset

### PR DESCRIPTION
**Pull request by realaeon**
-  add [RHD Dataset](https://lmb.informatik.uni-freiburg.de/resources/datasets/RenderedHandposeDataset.en.html)
- annotations are converted to coco style([download link](https://drive.google.com/file/d/1iBkF3srSQ0-LZhAPNlgOPxT-E8lT0vCY/view?usp=sharing)). and more details in [2d_hand_keypoint.md](https://github.com/realaeon/mmpose/blob/more_handdatasets/docs/tasks/2d_hand_keypoint.md#rhd-dataset)
- pose_resnet_50 results: "PCK": 0.98478, "AUC": 0.88716, "EPE": 2.66314

### CODE REVIEW

**Comment by jin-s13** [comment]
Thanks a lot for your contribution!

**Comment by innerlee** [comment]
Thanks! The code style looks good to me.

**Comment by realaeon** [comment]
Very happy to be involved in this project! I'm also working on STB hand dataset, and trying to make it work with 3d hand pose&mesh.

**Review by innerlee — APPROVED** [review]

**Comment by innerlee** [comment]
Thanks for your contribution! It's great!

**Pull request merged**
