### PR TITLE
[CodeCamp2023-533] Migration Deepfashion topdown heatmap algorithms to 1.x

### PR DESCRIPTION
**Pull request by xin-li-67**
## Motivation

[OpenMMLab Camp Task]https://github.com/open-mmlab/OpenMMLabCamp/discussions/533

## Modification

configs/fashion_2d_keypoint/topdown_heatmap/deepfashion/

## Checklist

**Before PR**:

- [x] I have read and followed the workflow indicated in the [CONTRIBUTING.md](https://github.com/open-mmlab/mmpose/blob/master/.github/CONTRIBUTING.md) to create this PR.
- [x] Pre-commit or linting tools indicated in [CONTRIBUTING.md](https://github.com/open-mmlab/mmpose/blob/master/.github/CONTRIBUTING.md) are used to fix the potential lint issues.
- [x] Bug fixes are covered by unit tests, the case that causes the bug should be added in the unit tests.
- [x] New functionalities are covered by complete unit tests. If not, please add more unit tests to ensure correctness.
- [x] The documentation has been modified accordingly, including docstring or example tutorials.

**After PR**:

- [x] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Comment by xin-li-67** [comment]
Question about this pr: only three res_50 chkpts were provided in the original 0.x branch. Do I need to train everything out and benchmark them by myself??

**Comment by Tau-J** [comment]
> Question about this pr: only three res_50 chkpts were provided in the original 0.x branch. Do I need to train everything out and benchmark them by myself??

Thanks for your feedback. I think it it okay if you only migrate the existed 3 ckpts. If you have time, I think training a strong baseline such as hrnet48+udp will be much appreciated.

**Comment by xin-li-67** [comment]
the test result of `td-hm_hrnet-w48_udp_8xb32-210e_deepfashion_full-256x192`:

```python
08/10 08:33:01 - mmengine - INFO - Distributed training is not used, all SyncBatchNorm (SyncBN) layers in the model will be automatically reverted to BatchNormXd layers if they are used.
08/10 08:33:01 - mmengine - INFO - Hooks will be executed in the following order:
before_run:
(VERY_HIGH   ) RuntimeInfoHook                    
(BELOW_NORMAL) LoggerHook                         
 -------------------- 
before_train:
(VERY_HIGH   ) RuntimeInfoHook                    
(NORMAL      ) IterTimerHook                      
(VERY_LOW    ) CheckpointHook                     
 -------------------- 
before_train_epoch:
(VERY_HIGH   ) RuntimeInfoHook                    
(NORMAL      ) IterTimerHook                      
(NORMAL      ) DistSamplerSeedHook                
 -------------------- 
before_train_iter:
(VERY_HIGH   ) RuntimeInfoHook                    
(NORMAL      ) IterTimerHook                      
 -------------------- 
after_train_iter:
(VERY_HIGH   ) RuntimeInfoHook                    
(NORMAL      ) IterTimerHook                      
(BELOW_NORMAL) LoggerHook                         
(LOW         ) ParamSchedulerHook                 
(VERY_LOW    ) CheckpointHook                     
 -------------------- 
after_train_epoch:
(NORMAL      ) IterTimerHook                      
(NORMAL      ) SyncBuffersHook                    
(LOW         ) ParamSchedulerHook                 
(VERY_LOW    ) CheckpointHook                     
 -------------------- 
before_val:
(VERY_HIGH   ) RuntimeInfoHook                    
 -------------------- 
before_val_epoch:
(NORMAL      ) IterTimerHook                      
(NORMAL      ) SyncBuffersHook                    
 -------------------- 
before_val_iter:
(NORMAL      ) IterTimerHook                      
 -------------------- 
after_val_iter:
(NORMAL      ) IterTimerHook                      
(NORMAL      ) PoseVisualizationHook              
(BELOW_NORMAL) LoggerHook                         
 -------------------- 
after_val_epoch:
(VERY_HIGH   ) RuntimeInfoHook                    
(NORMAL      ) IterTimerHook                      
(BELOW_NORMAL) LoggerHook                         
(LOW         ) ParamSchedulerHook                 
(VERY_LOW    ) CheckpointHook                     
 -------------------- 
after_val:
(VERY_HIGH   ) RuntimeInfoHook                    
 -------------------- 
after_train:
(VERY_HIGH   ) RuntimeInfoHook                    
(VERY_LOW    ) CheckpointHook                     
 -------------------- 
before_test:
(VERY_HIGH   ) RuntimeInfoHook                    
 -------------------- 
before_test_epoch:
(NORMAL      ) IterTimerHook                      
 -------------------- 
before_test_iter:
(NORMAL      ) IterTimerHook                      
 -------------------- 
after_test_iter:
(NORMAL      ) IterTimerHook                      
(NORMAL      ) PoseVisualizationHook              
(BELOW_NORMAL) LoggerHook                         
 -------------------- 
after_test_epoch:
(VERY_HIGH   ) RuntimeInfoHook                    
(NORMAL      ) IterTimerHook                      
(BELOW_NORMAL) LoggerHook                         
 -------------------- 
after_test:
(VERY_HIGH   ) RuntimeInfoHook                    
 -------------------- 
after_run:
(BELOW_NORMAL) LoggerHook                         
 -------------------- 
loading annotations into memory...
Done (t=0.03s)
creating index...
index created!
08/10 08:33:02 - mmengine - WARNING - The prefix is not set in metric class PCKAccuracy.
08/10 08:33:02 - mmengine - WARNING - The prefix is not set in metric class AUC.
08/10 08:33:02 - mmengine - WARNING - The prefix is not set in metric class EPE.
Loads checkpoint by local backend from path: work_dirs/td-hm_hrnet-w48_udp_8xb32-210e_deepfashion_full-256x192/best_AUC_epoch_180.pth
08/10 08:33:02 - mmengine - INFO - Load checkpoint from work_dirs/td-hm_hrnet-w48_udp_8xb32-210e_deepfashion_full-256x192/best_AUC_epoch_180.pth
08/10 08:33:04 - mmengine - INFO - Epoch(test) [ 10/253]    eta: 0:00:51  time: 0.211292  data_time: 0.030820  memory: 653  
08/10 08:33:05 - mmengine - INFO - Epoch(test) [ 20/253]    eta: 0:00:34  time: 0.146591  data_time: 0.017448  memory: 653  
08/10 08:33:06 - mmengine - INFO - Epoch(test) [ 30/253]    eta: 0:00:27  time: 0.125057  data_time: 0.012981  memory: 653  
08/10 08:33:07 - mmengine - INFO - Epoch(test) [ 40/253]    eta: 0:00:24  time: 0.115417  data_time: 0.010754  memory: 653  
08/10 08:33:08 - mmengine - INFO - Epoch(test) [ 50/253]    eta: 0:00:22  time: 0.109029  data_time: 0.009393  memory: 653  
08/10 08:33:09 - mmengine - INFO - Epoch(test) [ 60/253]    eta: 0:00:20  time: 0.083486  data_time: 0.004045  memory: 653  
08/10 08:33:09 - mmengine - INFO - Epoch(test) [ 70/253]    eta: 0:00:18  time: 0.085211  data_time: 0.004387  memory: 653  
08/10 08:33:10 - mmengine - INFO - Epoch(test) [ 80/253]    eta: 0:00:17  time: 0.086349  data_time: 0.004658  memory: 653  
08/10 08:33:11 - mmengine - INFO - Epoch(test) [ 90/253]    eta: 0:00:16  time: 0.086256  data_time: 0.004794  memory: 653  
08/10 08:33:12 - mmengine - INFO - Epoch(test) [100/253]    eta: 0:00:15  time: 0.087241  data_time: 0.004888  memory: 653  
08/10 08:33:13 - mmengine - INFO - Epoch(test) [110/253]    eta: 0:00:13  time: 0.088057  data_time: 0.004906  memory: 653  
08/10 08:33:14 - mmengine - INFO - Epoch(test) [120/253]    eta: 0:00:12  time: 0.086754  data_time: 0.004561  memory: 653  
08/10 08:33:15 - mmengine - INFO - Epoch(test) [130/253]    eta: 0:00:11  time: 0.085763  data_time: 0.004334  memory: 653  
08/10 08:33:16 - mmengine - INFO - Epoch(test) [140/253]    eta: 0:00:10  time: 0.086398  data_time: 0.004415  memory: 653  
08/10 08:33:16 - mmengine - INFO - Epoch(test) [150/253]    eta: 0:00:09  time: 0.086403  data_time: 0.004521  memory: 653  
08/10 08:33:17 - mmengine - INFO - Epoch(test) [160/253]    eta: 0:00:08  time: 0.086215  data_time: 0.004490  memory: 653  
08/10 08:33:18 - mmengine - INFO - Epoch(test) [170/253]    eta: 0:00:07  time: 0.086407  data_time: 0.004515  memory: 653  
08/10 08:33:19 - mmengine - INFO - Epoch(test) [180/253]    eta: 0:00:06  time: 0.087085  data_time: 0.004479  memory: 653  
08/10 08:33:20 - mmengine - INFO - Epoch(test) [190/253]    eta: 0:00:05  time: 0.086751  data_time: 0.004288  memory: 653  
08/10 08:33:21 - mmengine - INFO - Epoch(test) [200/253]    eta: 0:00:04  time: 0.086298  data_time: 0.004152  memory: 653  
08/10 08:33:22 - mmengine - INFO - Epoch(test) [210/253]    eta: 0:00:03  time: 0.086564  data_time: 0.004263  memory: 653  
08/10 08:33:22 - mmengine - INFO - Epoch(test) [220/253]    eta: 0:00:03  time: 0.087083  data_time: 0.004284  memory: 653  
08/10 08:33:23 - mmengine - INFO - Epoch(test) [230/253]    eta: 0:00:02  time: 0.087400  data_time: 0.004343  memory: 653  
08/10 08:33:24 - mmengine - INFO - Epoch(test) [240/253]    eta: 0:00:01  time: 0.087517  data_time: 0.004494  memory: 653  
08/10 08:33:25 - mmengine - INFO - Epoch(test) [250/253]    eta: 0:00:00  time: 0.087768  data_time: 0.004497  memory: 653  
08/10 08:33:25 - mmengine - INFO - Evaluating PCKAccuracy (normalized by ``"bbox_size"``)...
08/10 08:33:25 - mmengine - INFO - Evaluating AUC...
08/10 08:33:25 - mmengine - INFO - Evaluating EPE...
08/10 08:33:25 - mmengine - INFO - Epoch(test) [253/253]    PCK: 0.982517  AUC: 0.673234  EPE: 11.708903  data_time: 0.005471  time: 0.091295
```

**Comment by xin-li-67** [comment]
the test result of `td-hm_hrnet-w48_udp_8xb32-210e_deepfashion_lower-256x192.py`:
```python
08/10 08:28:40 - mmengine - INFO - Distributed training is not used, all SyncBatchNorm (SyncBN) layers in the model will be automatically reverted to BatchNormXd layers if they are used.
08/10 08:28:40 - mmengine - INFO - Hooks will be executed in the following order:
before_run:
(VERY_HIGH   ) RuntimeInfoHook                    
(BELOW_NORMAL) LoggerHook                         
 -------------------- 
before_train:
(VERY_HIGH   ) RuntimeInfoHook                    
(NORMAL      ) IterTimerHook                      
(VERY_LOW    ) CheckpointHook                     
 -------------------- 
before_train_epoch:
(VERY_HIGH   ) RuntimeInfoHook                    
(NORMAL      ) IterTimerHook                      
(NORMAL      ) DistSamplerSeedHook                
 -------------------- 
before_train_iter:
(VERY_HIGH   ) RuntimeInfoHook                    
(NORMAL      ) IterTimerHook                      
 -------------------- 
after_train_iter:
(VERY_HIGH   ) RuntimeInfoHook                    
(NORMAL      ) IterTimerHook                      
(BELOW_NORMAL) LoggerHook                         
(LOW         ) ParamSchedulerHook                 
(VERY_LOW    ) CheckpointHook                     
 -------------------- 
after_train_epoch:
(NORMAL      ) IterTimerHook                      
(NORMAL      ) SyncBuffersHook                    
(LOW         ) ParamSchedulerHook                 
(VERY_LOW    ) CheckpointHook                     
 -------------------- 
before_val:
(VERY_HIGH   ) RuntimeInfoHook                    
 -------------------- 
before_val_epoch:
(NORMAL      ) IterTimerHook                      
(NORMAL      ) SyncBuffersHook                    
 -------------------- 
before_val_iter:
(NORMAL      ) IterTimerHook                      
 -------------------- 
after_val_iter:
(NORMAL      ) IterTimerHook                      
(NORMAL      ) PoseVisualizationHook              
(BELOW_NORMAL) LoggerHook                         
 -------------------- 
after_val_epoch:
(VERY_HIGH   ) RuntimeInfoHook                    
(NORMAL      ) IterTimerHook                      
(BELOW_NORMAL) LoggerHook                         
(LOW         ) ParamSchedulerHook                 
(VERY_LOW    ) CheckpointHook                     
 -------------------- 
after_val:
(VERY_HIGH   ) RuntimeInfoHook                    
 -------------------- 
after_train:
(VERY_HIGH   ) RuntimeInfoHook                    
(VERY_LOW    ) CheckpointHook                     
 -------------------- 
before_test:
(VERY_HIGH   ) RuntimeInfoHook                    
 -------------------- 
before_test_epoch:
(NORMAL      ) IterTimerHook                      
 -------------------- 
before_test_iter:
(NORMAL      ) IterTimerHook                      
 -------------------- 
after_test_iter:
(NORMAL      ) IterTimerHook                      
(NORMAL      ) PoseVisualizationHook              
(BELOW_NORMAL) LoggerHook                         
 -------------------- 
after_test_epoch:
(VERY_HIGH   ) RuntimeInfoHook                    
(NORMAL      ) IterTimerHook                      
(BELOW_NORMAL) LoggerHook                         
 -------------------- 
after_test:
(VERY_HIGH   ) RuntimeInfoHook                    
 -------------------- 
after_run:
(BELOW_NORMAL) LoggerHook                         
 -------------------- 
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
08/10 08:28:41 - mmengine - WARNING - The prefix is not set in metric class PCKAccuracy.
08/10 08:28:41 - mmengine - WARNING - The prefix is not set in metric class AUC.
08/10 08:28:41 - mmengine - WARNING - The prefix is not set in metric class EPE.
Loads checkpoint by local backend from path: work_dirs/td-hm_hrnet-w48_udp_8xb32-210e_deepfashion_lower-256x192/best_AUC_epoch_180.pth
08/10 08:28:42 - mmengine - INFO - Load checkpoint from work_dirs/td-hm_hrnet-w48_udp_8xb32-210e_deepfashion_lower-256x192/best_AUC_epoch_180.pth
08/10 08:28:44 - mmengine - INFO - Epoch(test) [ 10/157]    eta: 0:00:29  time: 0.198109  data_time: 0.024492  memory: 653  
08/10 08:28:45 - mmengine - INFO - Epoch(test) [ 20/157]    eta: 0:00:19  time: 0.143357  data_time: 0.014357  memory: 653  
08/10 08:28:46 - mmengine - INFO - Epoch(test) [ 30/157]    eta: 0:00:15  time: 0.123881  data_time: 0.011017  memory: 653  
08/10 08:28:46 - mmengine - INFO - Epoch(test) [ 40/157]    eta: 0:00:13  time: 0.114912  data_time: 0.009298  memory: 653  
08/10 08:28:47 - mmengine - INFO - Epoch(test) [ 50/157]    eta: 0:00:11  time: 0.109820  data_time: 0.008227  memory: 653  
08/10 08:28:48 - mmengine - INFO - Epoch(test) [ 60/157]    eta: 0:00:10  time: 0.087698  data_time: 0.004204  memory: 653  
08/10 08:28:49 - mmengine - INFO - Epoch(test) [ 70/157]    eta: 0:00:08  time: 0.087339  data_time: 0.004148  memory: 653  
08/10 08:28:50 - mmengine - INFO - Epoch(test) [ 80/157]    eta: 0:00:07  time: 0.087805  data_time: 0.004094  memory: 653  
08/10 08:28:51 - mmengine - INFO - Epoch(test) [ 90/157]    eta: 0:00:06  time: 0.087564  data_time: 0.004048  memory: 653  
08/10 08:28:52 - mmengine - INFO - Epoch(test) [100/157]    eta: 0:00:05  time: 0.087191  data_time: 0.004163  memory: 653  
08/10 08:28:53 - mmengine - INFO - Epoch(test) [110/157]    eta: 0:00:04  time: 0.087060  data_time: 0.004085  memory: 653  
08/10 08:28:53 - mmengine - INFO - Epoch(test) [120/157]    eta: 0:00:03  time: 0.087025  data_time: 0.004102  memory: 653  
08/10 08:28:54 - mmengine - INFO - Epoch(test) [130/157]    eta: 0:00:02  time: 0.086341  data_time: 0.004104  memory: 653  
08/10 08:28:55 - mmengine - INFO - Epoch(test) [140/157]    eta: 0:00:01  time: 0.085424  data_time: 0.004195  memory: 653  
08/10 08:28:56 - mmengine - INFO - Epoch(test) [150/157]    eta: 0:00:00  time: 0.084366  data_time: 0.004150  memory: 653  
08/10 08:28:57 - mmengine - INFO - Evaluating PCKAccuracy (normalized by ``"bbox_size"``)...
08/10 08:28:57 - mmengine - INFO - Evaluating AUC...
08/10 08:28:57 - mmengine - INFO - Evaluating EPE...
08/10 08:28:57 - mmengine - INFO - Epoch(test) [157/157]    PCK: 0.977878  AUC: 0.761140  EPE: 8.928980  data_time: 0.005432  time: 0.093416
```

**Comment by xin-li-67** [comment]
the test result of `td-hm_hrnet-w48_udp_8xb32-210e_deepfashion_upper-256x192.py`:
```python
2023/08/10 08:26:19 - mmengine - INFO - Distributed training is not used, all SyncBatchNorm (SyncBN) layers in the model will be automatically reverted to BatchNormXd layers if they are used.
2023/08/10 08:26:19 - mmengine - INFO - Hooks will be executed in the following order:
before_run:
(VERY_HIGH   ) RuntimeInfoHook                    
(BELOW_NORMAL) LoggerHook                         
 -------------------- 
before_train:
(VERY_HIGH   ) RuntimeInfoHook                    
(NORMAL      ) IterTimerHook                      
(VERY_LOW    ) CheckpointHook                     
 -------------------- 
before_train_epoch:
(VERY_HIGH   ) RuntimeInfoHook                    
(NORMAL      ) IterTimerHook                      
(NORMAL      ) DistSamplerSeedHook                
 -------------------- 
before_train_iter:
(VERY_HIGH   ) RuntimeInfoHook                    
(NORMAL      ) IterTimerHook                      
 -------------------- 
after_train_iter:
(VERY_HIGH   ) RuntimeInfoHook                    
(NORMAL      ) IterTimerHook                      
(BELOW_NORMAL) LoggerHook                         
(LOW         ) ParamSchedulerHook                 
(VERY_LOW    ) CheckpointHook                     
 -------------------- 
after_train_epoch:
(NORMAL      ) IterTimerHook                      
(NORMAL      ) SyncBuffersHook                    
(LOW         ) ParamSchedulerHook                 
(VERY_LOW    ) CheckpointHook                     
 -------------------- 
before_val:
(VERY_HIGH   ) RuntimeInfoHook                    
 -------------------- 
before_val_epoch:
(NORMAL      ) IterTimerHook                      
(NORMAL      ) SyncBuffersHook                    
 -------------------- 
before_val_iter:
(NORMAL      ) IterTimerHook                      
 -------------------- 
after_val_iter:
(NORMAL      ) IterTimerHook                      
(NORMAL      ) PoseVisualizationHook              
(BELOW_NORMAL) LoggerHook                         
 -------------------- 
after_val_epoch:
(VERY_HIGH   ) RuntimeInfoHook                    
(NORMAL      ) IterTimerHook                      
(BELOW_NORMAL) LoggerHook                         
(LOW         ) ParamSchedulerHook                 
(VERY_LOW    ) CheckpointHook                     
 -------------------- 
after_val:
(VERY_HIGH   ) RuntimeInfoHook                    
 -------------------- 
after_train:
(VERY_HIGH   ) RuntimeInfoHook                    
(VERY_LOW    ) CheckpointHook                     
 -------------------- 
before_test:
(VERY_HIGH   ) RuntimeInfoHook                    
 -------------------- 
before_test_epoch:
(NORMAL      ) IterTimerHook                      
 -------------------- 
before_test_iter:
(NORMAL      ) IterTimerHook                      
 -------------------- 
after_test_iter:
(NORMAL      ) IterTimerHook                      
(NORMAL      ) PoseVisualizationHook              
(BELOW_NORMAL) LoggerHook                         
 -------------------- 
after_test_epoch:
(VERY_HIGH   ) RuntimeInfoHook                    
(NORMAL      ) IterTimerHook                      
(BELOW_NORMAL) LoggerHook                         
 -------------------- 
after_test:
(VERY_HIGH   ) RuntimeInfoHook                    
 -------------------- 
after_run:
(BELOW_NORMAL) LoggerHook                         
 -------------------- 
2023/08/10 08:26:20 - mmengine - WARNING - The prefix is not set in metric class PCKAccuracy.
2023/08/10 08:26:20 - mmengine - WARNING - The prefix is not set in metric class AUC.
2023/08/10 08:26:20 - mmengine - WARNING - The prefix is not set in metric class EPE.
2023/08/10 08:26:20 - mmengine - INFO - Load checkpoint from work_dirs/td-hm_hrnet-w48_udp_8xb32-210e_deepfashion_upper-256x192/best_AUC_epoch_60.pth
2023/08/10 08:26:22 - mmengine - INFO - Epoch(test) [ 10/215]    eta: 0:00:39  time: 0.190953  data_time: 0.015054  memory: 653  
2023/08/10 08:26:23 - mmengine - INFO - Epoch(test) [ 20/215]    eta: 0:00:27  time: 0.138505  data_time: 0.009926  memory: 653  
2023/08/10 08:26:24 - mmengine - INFO - Epoch(test) [ 30/215]    eta: 0:00:22  time: 0.120908  data_time: 0.008126  memory: 653  
2023/08/10 08:26:25 - mmengine - INFO - Epoch(test) [ 40/215]    eta: 0:00:19  time: 0.112188  data_time: 0.007313  memory: 653  
2023/08/10 08:26:26 - mmengine - INFO - Epoch(test) [ 50/215]    eta: 0:00:17  time: 0.106884  data_time: 0.006735  memory: 653  
2023/08/10 08:26:26 - mmengine - INFO - Epoch(test) [ 60/215]    eta: 0:00:16  time: 0.085739  data_time: 0.004548  memory: 653  
2023/08/10 08:26:27 - mmengine - INFO - Epoch(test) [ 70/215]    eta: 0:00:14  time: 0.085564  data_time: 0.004462  memory: 653  
2023/08/10 08:26:28 - mmengine - INFO - Epoch(test) [ 80/215]    eta: 0:00:13  time: 0.086059  data_time: 0.004660  memory: 653  
2023/08/10 08:26:29 - mmengine - INFO - Epoch(test) [ 90/215]    eta: 0:00:12  time: 0.086533  data_time: 0.004638  memory: 653  
2023/08/10 08:26:30 - mmengine - INFO - Epoch(test) [100/215]    eta: 0:00:11  time: 0.086434  data_time: 0.004531  memory: 653  
2023/08/10 08:26:31 - mmengine - INFO - Epoch(test) [110/215]    eta: 0:00:10  time: 0.086373  data_time: 0.004481  memory: 653  
2023/08/10 08:26:32 - mmengine - INFO - Epoch(test) [120/215]    eta: 0:00:08  time: 0.086331  data_time: 0.004440  memory: 653  
2023/08/10 08:26:32 - mmengine - INFO - Epoch(test) [130/215]    eta: 0:00:07  time: 0.085773  data_time: 0.004187  memory: 653  
2023/08/10 08:26:33 - mmengine - INFO - Epoch(test) [140/215]    eta: 0:00:07  time: 0.085171  data_time: 0.004088  memory: 653  
2023/08/10 08:26:34 - mmengine - INFO - Epoch(test) [150/215]    eta: 0:00:06  time: 0.085129  data_time: 0.004148  memory: 653  
2023/08/10 08:26:35 - mmengine - INFO - Epoch(test) [160/215]    eta: 0:00:05  time: 0.085315  data_time: 0.004287  memory: 653  
2023/08/10 08:26:36 - mmengine - INFO - Epoch(test) [170/215]    eta: 0:00:04  time: 0.085467  data_time: 0.004382  memory: 653  
2023/08/10 08:26:37 - mmengine - INFO - Epoch(test) [180/215]    eta: 0:00:03  time: 0.085638  data_time: 0.004503  memory: 653  
2023/08/10 08:26:38 - mmengine - INFO - Epoch(test) [190/215]    eta: 0:00:02  time: 0.085708  data_time: 0.004574  memory: 653  
2023/08/10 08:26:38 - mmengine - INFO - Epoch(test) [200/215]    eta: 0:00:01  time: 0.085860  data_time: 0.004648  memory: 653  
2023/08/10 08:26:39 - mmengine - INFO - Epoch(test) [210/215]    eta: 0:00:00  time: 0.085802  data_time: 0.004645  memory: 653  
2023/08/10 08:26:40 - mmengine - INFO - Evaluating PCKAccuracy (normalized by ``"bbox_size"``)...
2023/08/10 08:26:40 - mmengine - INFO - Evaluating AUC...
2023/08/10 08:26:40 - mmengine - INFO - Evaluating EPE...
2023/08/10 08:26:40 - mmengine - INFO - Epoch(test) [215/215]    PCK: 0.961163  AUC: 0.608919  EPE: 15.125773  data_time: 0.004980  time: 0.090711
```

**Comment by xin-li-67** [comment]
Wandb Traning logs are available here: https://api.wandb.ai/links/xinliritz80/awwme4nf

**Review by Tau-J — APPROVED** [review]
LGTM

**Pull request merged**
