### PR TITLE
Merge ae-test to ae-train

### PR DESCRIPTION
**Pull request by wusize**
## Checklist

**Before PR**:

- [ ] I have read and followed the workflow indicated in the [CONTRIBUTING.md](https://github.com/open-mmlab/mmpose/blob/master/.github/CONTRIBUTING.md) to create this PR.
- [ ] Pre-commit or linting tools indicated in [CONTRIBUTING.md](https://github.com/open-mmlab/mmpose/blob/master/.github/CONTRIBUTING.md) are used to fix the potential lint issues.
- [ ] Bug fixes are covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] New functionalities are covered by complete unit tests. If not, please add more unit tests to ensure correctness.
- [ ] The documentation has been modified accordingly, including docstring or example tutorials.

**After PR**:

- [ ] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Comment by wusize** [comment]
Please let me first merge Yining's ae-test brach to ae-train

**Comment by Ben-Louis** [comment]
I have rebased 'ae-test' onto 'ae-train', resolving conflicts. However, the new feature enabling folder paths as inputs caused the bottom-up demo script to fail. Given its non-essential role in AE replication, I've temporarily removed this feature. Now, the script functions correctly with the AE model, producing reasonable outputs.

**Comment by ly015** [comment]
Is the branch ae-train checked out from the latest main or dev?

**Comment by wusize** [comment]
dev

**Pull request merged**
