### PR TITLE
Reorganize configs by tasks, algorithms, datasets, model settings, and techniques

### PR DESCRIPTION
**Pull request by jin-s13**
1. The config files are organized as `configs/{topic}/{task}/{algorithm}/{dataset}/{backbone}_[model_setting]_{dataset}_[input_size]_[technique].py`
2. Use `_result` to record raw results of a specific setting (backbone + dataset + technique), which need to fill in manually.
3. Use `configs/README/*` to collect the results and automatically create the modelzoo leaderboard. Will add a link to the readthedocs/modelzoo
4. Add `<Algorithm>` `<Dataset>` tags to the result.md.
5. Add `docs/collect.py` to create the modelzoo leaderboard.

Supported topic list (2021.05.20):
```
1. animal
2. body
3. face
4. fashion
5. hand
6. wholebody
```

Supported task list (2021.05.20):
```
1. 2d_kpt_sview_rgb_img: This means the output is 2D keypoint; the input is single-view (sview) RGB image (img).
2. 3d_kpt_sview_rgb_img: This means the output is 3D keypoint; the input is single-view (sview) RGB image (img).
3. 3d_kpt_sview_rgb_vid: This means the output is 3D keypoint; the input is single-view (sview) RGB video sequences (vid).
4. 3d_mesh_sview_rgb_img: This means the output is 3D mesh; the input is single-view (sview) RGB image (img).
```

### CODE REVIEW

**Comment by innerlee** [comment]
image

image

1. `SV` is hard to guess. How about "SView"?
2. What is a `hm` ? human?
2. I don't understand the role of the `_result` and `_result_collection`. 
3. `class` can be renamed to `topic`/`theme`/...
4. Should list all options of `task` in obvious places, such as the top-post in this thread.

**Comment by jin-s13** [comment]
1. `SV` to `SView`
2. `topdown_hm` to `topdown_heatmap`
3. `class` to `topic`

**Comment by innerlee** [comment]
In addition, and again the AE could be associative-embedding, or autoencoder. I prefer "associative_embedding", but you decide which to use. It's okay to use "ae" if that does not bother u.

image

BTW I still have some questions on the `_result`, we may discuss later.

**Review by innerlee — APPROVED** [review]

**Comment by innerlee** [comment]
Need to update links in README to appropriate url in readthedocs, since real contents are dynamically generated.

**Review by ly015 — APPROVED** [review]

**Pull request merged**
