### PR TITLE
Add a jupyter tutorial for google colab

### PR DESCRIPTION
**Pull request by ly015**

### CODE REVIEW

**Comment by innerlee** [comment]
Currently this file is very large. Try to change png to jpg. I guess the file size could be reduced.

image

**Comment by innerlee** [comment]
@ly015 have you actually run the notebook on colab?

**Comment by ly015** [comment]
> @ly015 have you actually run the notebook on colab?

Yes.

**Comment by ly015** [comment]
> Also add a small logo to the file. See https://github.com/open-mmlab/mmocr/blob/main/demo/MMOCR_Tutorial.ipynb
> 
> image

Done.

**Review by jin-s13 — APPROVED** [review]

**Pull request merged**
