### PR TITLE
udp for bottom_up pipeline

### PR DESCRIPTION
**Pull request by HuangJunJie2017**
udp for bottom_up pipeline
i add udp by adding new paralleled modules which have no effect on the previous works

### CODE REVIEW

**Comment by innerlee** [comment]
For easier review, i will post the major differences here

image

**Comment by innerlee** [comment]
image

**Comment by HuangJunJie2017** [comment]
@innerlee i haven't directly modified the original modules in propose of maintaining the implementation of previous works~
now i am dealing with the problems of pylint~

**Comment by HuangJunJie2017** [comment]
@innerlee shall I cancel this PR and make another PR after addressing the problem in pylint?

**Comment by innerlee** [comment]
no, simply push more commits here

**Comment by HuangJunJie2017** [comment]
@innerlee ok, i push another commit for this
by the way, do you need the pretrained models & train logs?

**Comment by innerlee** [comment]
Not yet, let's go through the codes first :D

**Comment by innerlee** [comment]
image

**Comment by innerlee** [comment]
HeatmapParser_udp

image

**Comment by innerlee** [comment]
image

where the `adjust` was replaced by `post_dark`

**Comment by HuangJunJie2017** [comment]
What's the meaning of the following comments? 

flake8...................................................................Passed
seed isort known_third_party.............................................Passed
isort....................................................................Failed
- hook id: isort
- files were modified by this hook

Fixing mmpose/models/detectors/bottom_up.py
Fixing mmpose/datasets/pipelines/bottom_up_transform.py
Fixing mmpose/core/evaluation/bottom_up_eval.py

yapf.....................................................................Failed
- hook id: yapf
- files were modified by this hook
Trim Trailing Whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook

Fixing configs_udp/bottom_up/higherhrnet/README.md
Fixing configs_udp/bottom_up/hrnet/README.md

Check Yaml...............................................................Passed
Fix End of Files.........................................................Failed
- hook id: end-of-file-fixer
- exit code: 1
- files were modified by this hook

Fixing configs_udp/bottom_up/higherhrnet/README.md

Fix requirements.txt.....................................................Passed
Fix double quoted strings................................................Passed
Check for merge conflicts................................................Passed
Fix python encoding pragma...............................................Passed
Mixed line ending........................................................Passed
docformatter.............................................................Failed
- hook id: docformatter
- files were modified by this hook

**Comment by innerlee** [comment]
in bottom_up_transform.py 

image

**Comment by innerlee** [comment]
pre-commit will auto format your code. So you can add and commit the changes

**Comment by HuangJunJie2017** [comment]
any further modification is needed? build/lint is still not successful~

**Comment by innerlee** [comment]
image

**Comment by innerlee** [comment]
Ignore the linting for now. The structure might undergo big change.

I will post the changes as above, and assess whether we will add separate classes/functions for udp, or add a switch in the previous classes/functions.

**Comment by HuangJunJie2017** [comment]
ok, i will prepare the udp for top-down paradigm and push it in this PR few minutes later?

**Comment by innerlee** [comment]
image

**Comment by innerlee** [comment]
For top-down, I suggest make a new pr. In that pr, you can change the code "inplace", and keep the diff minimum. The result diff will be similar to the pictures I posted above. 

That will help the review~

**Comment by HuangJunJie2017** [comment]
ok

**Comment by innerlee** [comment]
image

**Comment by innerlee** [comment]
image

**Comment by innerlee** [comment]
image

**Comment by innerlee** [comment]
image

**Comment by innerlee** [comment]
Main changes have been posted. Let's see what's the best way to integrate it. What do you think @HuangJunJie2017 @jin-s13 ?

**Comment by HuangJunJie2017** [comment]
emmm, at first i prepare it 'inplace' ,but i notice that one of the main purposes of this report is to help other reproducing the sotas(not only udp), so i change it into 'parallel'~

**Comment by HuangJunJie2017** [comment]
'parallel' means many redundant code, consider another branch 'udp' in parallel with 'master'?

**Comment by innerlee** [comment]
Yep, reproducing sota will be guaranteed here. In the meantime, we want the codebase to be simple and easy to digest.

One way to achieve this is by configs.

* For simple changes, E.g., in the first picture for `get_multi_stage_outputs_udp`, you can make the `align_corners` an argument of the function
* For new processings, we can add an UDP version, and choose it in the config file
* For classes, object heritance might be helpful too

**Comment by innerlee** [comment]
Say if you have udp v2 and v3, we cannot just duplicate codes four times. ᥬ🌝᭄

**Comment by HuangJunJie2017** [comment]
emm, now the data processing pipeline has been unbiased~, so, there will not be  v2 or v3~

**Comment by jin-s13** [comment]
> Main changes have been posted. Let's see what's the best way to integrate them. What do you think @HuangJunJie2017 @jin-s13 ?

Yes. To make the codes simple, we can add a switch `use_udp` to integrate these two parts. Most of the codes can be shared. 
It seems that `HeatmapGenerator` and `get_warpmatrix` are the main diff, others can be integrated first.

**Comment by HuangJunJie2017** [comment]
so~ the switch is the final decision?
and i make another PR instead of modify this?

**Comment by jin-s13** [comment]
> so~ the switch is the final decision?
> and i make another PR instead of modify this?

Yes. Please use a switch variable `use_udp`  and some if-else conditions to achieve this.
Making another PR will be better.

**Pull request closed without merging**
