### PR TITLE
[Refactor] disentangle the 2d keypoint head from `DetectAndRegress` in multiview pose

### PR DESCRIPTION
**Pull request by wusize**
## Motivation
The backbone in multiview_pose.[DetectAndRegress ](https://github.com/open-mmlab/mmpose/blob/master/mmpose/models/detectors/multiview_pose.py)consists a 2d keypoint_head (e.g. a deconvhead), which should be split out.

## Modification
mmpose/models/detectors/multiview_pose.py

## Checklist

**Before PR**:

- [ ] I have read and followed the workflow indicated in the [CONTRIBUTING.md](https://github.com/open-mmlab/mmpose/blob/master/.github/CONTRIBUTING.md) to create this PR.
- [ ] Pre-commit or linting tools indicated in [CONTRIBUTING.md](https://github.com/open-mmlab/mmpose/blob/master/.github/CONTRIBUTING.md) are used to fix the potential lint issues.
- [ ] Bug fixes are covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] New functionalities are covered by complete unit tests. If not, please add more unit tests to ensure correctness.
- [ ] The documentation has been modified accordingly, including docstring or example tutorials.

**After PR**:

- [ ] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Review by jin-s13 — APPROVED** [review]

**Comment by ly015** [comment]
@wusize Could you please rebase the PR branch to `dev-0.28`? And the CI failed and may need a check.

**Review by jin-s13 — CHANGES_REQUESTED** [review]
maybe rebase error.

**Review by jin-s13 — APPROVED** [review]

**Comment by ly015** [comment]
@wusize Could you please modify `mmpose/__init__.py` and set `maximum_mmcv_version=1.7.0` to avoid the CI failure?

**Comment by ly015** [comment]
@wusize The mmcv version issue has been fixed in the master branch. But it's better not to rebase onto the master now since it may cause confusion when merging dev-0.29 to master.

**Comment by ly015** [comment]
The mmcv version issue has also been fixed in dev-0.29. Please rebase this PR to enable CI.

**Pull request closed without merging**
