### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jin-s13**
fix typos.

### CODE REVIEW

**Comment by innerlee** [comment]
the diff shows typo fixes in readme, and nothing in test/data has changed.

**Comment by jin-s13** [comment]
> the diff shows typo fixes in readme, and nothing in test/data has changed.

Yes. Only the typos.

**Comment by innerlee** [comment]
not related to this pr, but how about adding links to their corresponding configs on the names, like

image

**Comment by jin-s13** [comment]
> not related to this pr, but how about adding links to their corresponding configs on the names, like
> 
> image

Let me try.

**Comment by innerlee** [comment]
For the links, write the path from the repo root, which starts with a leading slash /. in this way, the docs site would be smart enough to link back to this repo.

image

**Pull request merged**
