### PR TITLE
Update runtime.txt

### PR DESCRIPTION
**Pull request by innerlee**

### CODE REVIEW

**Comment by innerlee** [comment]
@jin-s13 could you verify that we can run using the latest pillow? v7.1.0 i guess

**Comment by jin-s13** [comment]
We use pillow==6.2.2 to be compatible with [mmdetection requirement](https://github.com/open-mmlab/mmdetection/blob/master/requirements/runtime.txt), which requires `Pillow<=6.2.2`

**Comment by innerlee** [comment]
@hellock can mmdet upgrade pillow to higher version?

**Comment by hellock** [comment]
> @hellock can mmdet upgrade pillow to higher version?

This version requirement can be removed.

**Pull request merged**
