### PR TITLE
[Feature] Add AP-10K dataset and models

### PR DESCRIPTION
**Pull request by Annbless**
## Motivation

This PR is to merge the largest dataset for animal pose estimation (AP-10K) into mmpose. This PR contains the training configs and description of the main experiments existing in the AP-10K dataset and paper. The new dataset will benefit future research in animal pose estimation.

## Modification

1. In the `docs` folder and `READEME` file, add the description of the proposed AP-10K dataset;
2. In the `configs` folder, add corresponding config files for training SimpleBaseline with ResNet-50/101 and HRNet-w32/48 with AP-10K dataset.
3. To do: add links to the corresponding logs and pretrained models under the `config` folder 

## Checklist

**Before PR**:

- [x] I have read and followed the workflow indicated in the [CONTRIBUTING.md](https://github.com/open-mmlab/mmpose/blob/master/.github/CONTRIBUTING.md) to create this PR.
- [x] Pre-commit or linting tools indicated in [CONTRIBUTING.md](https://github.com/open-mmlab/mmpose/blob/master/.github/CONTRIBUTING.md) are used to fix the potential lint issues.
- [x] Bug fixes are covered by unit tests, the case that causes the bug should be added in the unit tests.
- [x] New functionalities are covered by complete unit tests. If not, please add more unit tests to ensure correctness.
- [x] The documentation has been modified accordingly, including docstring or example tutorials.

**After PR**:

- [x] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Comment by Annbless** [comment]
Hi, we found that we made a typo in the code. The [sigma values](https://github.com/open-mmlab/mmpose/blob/master/configs/_base_/datasets/ap10k.py#L143) in `_base_/datasets/ap10k.py' in order is wrong. 
Please correct it to 

`    sigmas=[
        0.025, 0.025, 0.026, 0.035, 0.035, 0.079, 0.072, 0.062, 0.079, 0.072,
        0.062, 0.107, 0.087, 0.089, 0.107, 0.087, 0.089
    ])
`

Thanks again!

Best,
Yufei

**Comment by jin-s13** [comment]
OK. I will correct it.

**Comment by jin-s13** [comment]
BTW, as the sigmas are changed, do we need to change the reported performance in the modelzoo?  @Annbless

**Comment by Annbless** [comment]
No need. We have tested the average precision using the two settings and the results are quite similar. Thanks again.

**Comment by OpenMMLab-Team** [comment]
Hi @Annbless ！First of all, we want to express our gratitude for your significant PR in the MMpose project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA

If you have WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution!❤

**Pull request merged**
