### PR TITLE
unify use_gt in configs

### PR DESCRIPTION
**Pull request by jin-s13**

### CODE REVIEW

**Comment by innerlee** [comment]
is this a typo-fix?

**Comment by jin-s13** [comment]
Some cfgs use_gt=False, while others use_gt=True.  Better use the same setting.

**Comment by innerlee** [comment]
Does this setting affect training? Will they also affect provided weights in modelzoo?

**Comment by jin-s13** [comment]
Just the evaluation settings. This will not affect training and the provided weights. 
However, in the accompanied log, the testing accuracy will be different...

**Comment by jin-s13** [comment]
No. Only the log will be affected. Model zoo will not.

**Pull request merged**
